chore: try removing all brew install steps
(hdf5 provides proper wheels now)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -174,29 +174,29 @@ jobs:
       run: |
         cd build_helpers && ./install_ta-lib.sh ${HOME}/dependencies/; cd ..
 
-    - name: Installation - macOS (Brew)
-      run: |
-        # brew update
-        # TODO: Should be the brew upgrade
-        # homebrew fails to update python due to unlinking failures
-        # https://github.com/actions/runner-images/issues/6817
-        rm /usr/local/bin/2to3 || true
-        rm /usr/local/bin/2to3-3.11 || true
-        rm /usr/local/bin/2to3-3.12 || true
-        rm /usr/local/bin/idle3 || true
-        rm /usr/local/bin/idle3.11 || true
-        rm /usr/local/bin/idle3.12 || true
-        rm /usr/local/bin/pydoc3 || true
-        rm /usr/local/bin/pydoc3.11 || true
-        rm /usr/local/bin/pydoc3.12 || true
-        rm /usr/local/bin/python3 || true
-        rm /usr/local/bin/python3.11 || true
-        rm /usr/local/bin/python3.12 || true
-        rm /usr/local/bin/python3-config || true
-        rm /usr/local/bin/python3.11-config || true
-        rm /usr/local/bin/python3.12-config || true
+    # - name: Installation - macOS (Brew)
+    #   run: |
+    #     # brew update
+    #     # TODO: Should be the brew upgrade
+    #     # homebrew fails to update python due to unlinking failures
+    #     # https://github.com/actions/runner-images/issues/6817
+    #     rm /usr/local/bin/2to3 || true
+    #     rm /usr/local/bin/2to3-3.11 || true
+    #     rm /usr/local/bin/2to3-3.12 || true
+    #     rm /usr/local/bin/idle3 || true
+    #     rm /usr/local/bin/idle3.11 || true
+    #     rm /usr/local/bin/idle3.12 || true
+    #     rm /usr/local/bin/pydoc3 || true
+    #     rm /usr/local/bin/pydoc3.11 || true
+    #     rm /usr/local/bin/pydoc3.12 || true
+    #     rm /usr/local/bin/python3 || true
+    #     rm /usr/local/bin/python3.11 || true
+    #     rm /usr/local/bin/python3.12 || true
+    #     rm /usr/local/bin/python3-config || true
+    #     rm /usr/local/bin/python3.11-config || true
+    #     rm /usr/local/bin/python3.12-config || true
 
-        brew install hdf5 c-blosc libomp
+    #     brew install hdf5 c-blosc libomp
 
     - name: Installation (python)
       run: |
